# Generated by Django 3.1.3 on 2020-11-22 16:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_birthdate_gender_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cases_description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
