# Generated by Django 3.1.3 on 2020-11-22 16:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_add_ck_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cases_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
    ]
