# Generated by Django 3.1.3 on 2020-11-28 17:47

import cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_add_description_to_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=cases.models.get_upload_path)),
                ('document_type', models.PositiveSmallIntegerField(choices=[(1, 'Treatment'), (2, 'Prescription'), (3, 'Diagnosis')], default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('user', models.ForeignKey(editable=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='cases.user')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
