# Generated by Django 3.1.3 on 2020-11-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_mylibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.document'),
        ),
    ]
