# Generated by Django 3.1.3 on 2020-11-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_add_foreign_key_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='documents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cases.document'),
            preserve_default=False,
        ),
    ]
