# Generated by Django 3.1.3 on 2020-11-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_on_delete_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylibrary',
            name='documents',
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cases.document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.user'),
        ),
    ]
