# Generated by Django 3.1.3 on 2020-11-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_remove_some_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.document', unique=True),
        ),
        migrations.CreateModel(
            name='BookmarkedCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.user')),
            ],
        ),
    ]
