# Generated by Django 3.1.3 on 2020-11-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_add_bookmarked_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkedcases',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.document'),
        ),
    ]
